# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: providerSearchEnv
  displayName: Download env file
  inputs:
    secureFile: provider-search.env.staging
- script: ls $(providerSearchEnv.secureFilePath)
  displayName: 'show secure files'
- task: CopyFiles@2
  inputs:
    SourceFolder: $(providerSearchEnv.secureFilePath)
    Contents: '**'
    TargetFolder: $(Build.SourcesDirectory)
    OverWrite: true
- script: ls 
  displayName: 'show files'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
