# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
- main

pool:
  vmImage: ubuntu-latest

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      - name: envFile
        value: provider-search.env.staging
      - name: deployPath
        value: /var/www/html/providersearch/staging
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - name: envFile
        value: provider-search.env.production
      - name: deployPath
        value: /var/www/html/providersearch/production

steps:
- task: DownloadSecureFile@1
  name: providerSearchEnv
  displayName: Download env file
  inputs:
    secureFile: $(envFile)
- script: cp $(providerSearchEnv.secureFilePath) $(System.DefaultWorkingDirectory)/.env
  displayName: 'Copy env file'
- script: composer install --ignore-platform-reqs
  displayName: 'Composer install'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: php artisan storage:link
  displayName: 'Setup file storage'
  workingDirectory: $(System.DefaultWorkingDirectory)
- task: Npm@1
  displayName: 'Npm Install'
  inputs:
    command: install
    workingDir: $(System.DefaultWorkingDirectory)
- task: Npm@1
  displayName: 'Npm build'
  inputs:
    command: custom
    customCommand: run prod
    workingDir: $(System.DefaultWorkingDirectory)
- task: ArchiveFiles@2
  displayName: Package
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/provider-search_$(Build.BuildId).zip
    replaceExistingArchive: true
- publish: $(Build.ArtifactStagingDirectory)/provider-search_$(Build.BuildId).zip
  artifact: drop
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: ProviderSearchVm
    sourceFolder: $(System.DefaultWorkingDirectory)
    contents: '**'
    targetFolder: $(deployPath)
    readyTimeout: '20000'
    overwrite: true

