# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  - name: srcPath
    value: /home/providersearch/src
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      - name: envFile
        value: provider-search.env.staging
      - name: environment
        value: staging
      - name: deployPath
        value: /var/www/html/providersearch/staging
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - name: envFile
        value: provider-search.env.production
      - name: environment
        value: prod
      - name: deployPath
        value: /var/www/html/providersearch/production

steps:
- task: DownloadSecureFile@1
  name: providerSearchEnv
  displayName: Download env file
  inputs:
    secureFile: $(envFile)
- script: cp $(providerSearchEnv.secureFilePath) $(System.DefaultWorkingDirectory)/.env
  displayName: 'Copy env file'
- task: ArchiveFiles@2
  displayName: Package
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/provider-search_$(Build.BuildId).zip
    replaceExistingArchive: true
- publish: $(Build.ArtifactStagingDirectory)/provider-search_$(Build.BuildId).zip
  artifact: drop
- task: CopyFilesOverSSH@0
  displayName: Deploy
  inputs:
    sshEndpoint: ProviderSearchVm
    sourceFolder: $(Build.ArtifactStagingDirectory)
    contents: '**/*.zip'
    targetFolder: $(srcPath)
    readyTimeout: '20000'
    overwrite: true
    cleanTargetFolder: true
- task: SSH@0
  displayName: Unzip files
  inputs:
    sshEndpoint: ProviderSearchVm
    runOptions: 'inline'
    inline: unzip -o $(srcPath)/provider-search_$(Build.BuildId).zip -d $(srcPath)/$(environment)
- task: SSH@0
  displayName: Build
  inputs:
    sshEndpoint: ProviderSearchVm
    runOptions: 'script'
    scriptPath: $(srcPath)/.devops.sh
- task: SSH@0
  displayName: Clear cache
  inputs:
    sshEndpoint: ProviderSearchVm
    runOptions: 'inline'
    inline: sudo rm -rf $(deployPath)/storage
- task: SSH@0
  displayName: Clear cache
  inputs:
    sshEndpoint: ProviderSearchVm
    runOptions: 'inline'
    inline: sudo cp -rf $(srcPath)/$(environment) $(deployPath)
- task: SSH@0
  displayName: Update file owner
  inputs:
    sshEndpoint: ProviderSearchVm
    runOptions: 'inline'
    inline: sudo chown -R www-data:www-data $(deployPath)



