# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: providerSearchEnv
  displayName: Download env file
  inputs:
    secureFile: provider-search.env.staging
- script: cp $(providerSearchEnv.secureFilePath) $(Build.SourcesDirectory)/.env
  displayName: 'copy env file'
- script: chmod +x ./scripts/devops.sh
  displayName: 'update devops script permissions'
- script: make devops
  displayName: 'Build project for deployment'
  workingDirectory: $(System.DefaultWorkingDirectory)
- task: ArchiveFiles@2
  displayName: Package
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/provider-search_$(Build.BuildId).zip
    replaceExistingArchive: true
- publish: $(Build.ArtifactStagingDirectory)/provider-search_$(Build.BuildId).zip
  artifact: drop

