# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

# More GitHub Actions for Azure: https://github.com/Azure/actions



name: Build and deploy PHP app to Azure Web App - provider-search-prod



on:
  push:
    branches:
      - develop
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: providersearchacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
        docker build -f .github/workflows/build-and-deploy/Dockerfile . -t providersearchacr.azurecr.io/providersearch:production
        docker push providersearchacr.azurecr.io/providersearch:production
